# Generated by Django 4.2.17 on 2025-04-10 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Transaction Amount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='pending', max_length=20, verbose_name='Transaction Status')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Daily Contribution',
                'verbose_name_plural': 'Daily Contributions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FailedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_reason', models.CharField(max_length=500)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolution Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Resolution Notes')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.dailycontribution')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
            ],
            options={
                'verbose_name': 'Failed Transaction',
                'verbose_name_plural': 'Failed Transactions',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargebackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('explanation', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'SUBMITTED'), ('under_review', 'UNDER_REVIEW'), ('resolved', 'RESOLVED'), ('rejected', 'REJECTED')], default='submitted', max_length=20)),
                ('review_time', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('failed_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.failedtransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'Chargeback Form',
                'verbose_name_plural': 'Chargeback Forms',
                'ordering': ['-submission_time'],
            },
        ),
    ]
