# Generated by Django 4.2.17 on 2025-04-11 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('from_email', models.EmailField(max_length=254, verbose_name='From Email')),
                ('recipient', models.TextField(verbose_name='Recipient Email')),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Date Sent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
