# Generated by Django 4.2.17 on 2025-04-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='notification',
            name='ref_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
