# Generated by Django 4.2.17 on 2025-04-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_notification_options_notification_ref_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='ref_id',
        ),
        migrations.AddField(
            model_name='chargebackform',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.notification'),
        ),
        migrations.AddField(
            model_name='dailycontribution',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.notification'),
        ),
        migrations.AddField(
            model_name='failedtransaction',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.notification'),
        ),
    ]
