# Generated by Django 4.2.17 on 2025-04-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_notification_ref_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('under_review', 'UNDER_REVIEW'), ('resolved', 'RESOLVED'), ('rejected', 'REJECTED')], default='pending', max_length=20),
        ),
    ]
