# Generated by Django 4.2.17 on 2025-04-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_failedtransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedtransaction',
            name='charge_back_submitted',
            field=models.BooleanField(default=False, verbose_name='Chargeback Submitted'),
        ),
    ]
